const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  appVersion: () => ipcRenderer.invoke("app:version"),
  getConfig: () => ipcRenderer.invoke("config:get"),
  setConfig: (cfg) => ipcRenderer.invoke("config:set", cfg),
  next: () => ipcRenderer.invoke("wp:next"),
  info: () => ipcRenderer.invoke("wp:info"),
  clearCache: () => ipcRenderer.invoke("cache:clear"),
  cacheInfo: () => ipcRenderer.invoke("cache:info"),
  cacheOpenDir: () => ipcRenderer.invoke("cache:openDir"),
  cachePickDir: () => ipcRenderer.invoke("cache:pickDir"),
  cacheSetDir: (opts) => ipcRenderer.invoke("cache:setDir", opts),
  folderSources: (opts) => ipcRenderer.invoke("folder:sources", opts || {}),
  folderAddSource: () => ipcRenderer.invoke("folder:addSource"),
  folderRemoveSource: (opts) => ipcRenderer.invoke("folder:removeSource", opts),

  history: () => ipcRenderer.invoke("history:get"),
  historySetFromFile: (item) => ipcRenderer.invoke("history:setFromFile", item),
  historyRemove: (item) => ipcRenderer.invoke("history:remove", item),
  openExternal: (u) => ipcRenderer.invoke("open:external", u),
  showInFolder: (f) => ipcRenderer.invoke("show:inFolder", f),
  fetchTags: (opts) => ipcRenderer.invoke("tags:fetch", opts),
  whCollections: (opts) => ipcRenderer.invoke("wh:collections", opts),
  whCollectionItems: (opts) => ipcRenderer.invoke("wh:collectionItems", opts),
  whOpenFavorite: (opts) => ipcRenderer.invoke("wh:openFavorite", opts),
  // Static browse
  searchRun: (opts) => ipcRenderer.invoke("search:run", opts),
  setFromRemote: (w) => ipcRenderer.invoke("wp:setFromRemote", w),
  // Local playlists
  playlistList: () => ipcRenderer.invoke("playlist:list"),
  playlistCreate: (opts) => ipcRenderer.invoke("playlist:create", opts),
  playlistDelete: (opts) => ipcRenderer.invoke("playlist:delete", opts),
  playlistRename: (opts) => ipcRenderer.invoke("playlist:rename", opts),
  playlistAddItem: (opts) => ipcRenderer.invoke("playlist:addItem", opts),
  playlistRemoveItem: (opts) => ipcRenderer.invoke("playlist:removeItem", opts),
  playlistReorder: (opts) => ipcRenderer.invoke("playlist:reorder", opts),
  playlistSetActive: (opts) => ipcRenderer.invoke("playlist:setActive", opts),
  // v0.2.0 — likes, dislikes, schedule, updater
  like: () => ipcRenderer.invoke("wp:like"),
  likeItem: (item) => ipcRenderer.invoke("wp:likeItem", item),
  setWallpaperReaction: (opts) => ipcRenderer.invoke("wp:setReaction", opts),
  likes: () => ipcRenderer.invoke("wp:likes"),
  dislike: () => ipcRenderer.invoke("wp:dislike"),
  clearDislikes: () => ipcRenderer.invoke("wp:clearDislikes"),
  clearLikes: () => ipcRenderer.invoke("wp:clearLikes"),
  schedulePreview: () => ipcRenderer.invoke("schedule:preview"),
  updateCheck: () => ipcRenderer.invoke("update:check"),
  updateDismiss: (v) => ipcRenderer.invoke("update:dismiss", v),
  updateDownload: () => ipcRenderer.invoke("update:download"),
  updateInstall: () => ipcRenderer.invoke("update:install"),
  updateInfo: () => ipcRenderer.invoke("update:info"),
  onUpdateStatus: (cb) => ipcRenderer.on("update-status", (_e, s) => cb(s)),
  changelog: () => ipcRenderer.invoke("app:changelog"),
  fullscreenProbe: () => ipcRenderer.invoke("fullscreen:probe"),
  appsRunning: () => ipcRenderer.invoke("apps:running"),
  cacheTest: (opts) => ipcRenderer.invoke("cache:test", opts || {}),
  // Pass 2 — portable, folders, export, tags, hotkeys
  portableInfo: () => ipcRenderer.invoke("app:portable"),
  folderPick: () => ipcRenderer.invoke("folder:pick"),
  folderCloudRoots: () => ipcRenderer.invoke("folder:cloudRoots"),
  folderAddKnown: (folderPath) => ipcRenderer.invoke("folder:addKnown", { folderPath }),
  folderImportAsPlaylist: (opts) => ipcRenderer.invoke("folder:importAsPlaylist", opts),
  playlistExport: (opts) => ipcRenderer.invoke("playlist:export", opts),
  playlistSetItemTags: (opts) => ipcRenderer.invoke("playlist:setItemTags", opts),
  playlistSetTagFilter: (opts) => ipcRenderer.invoke("playlist:setTagFilter", opts),
  hotkeysReregister: () => ipcRenderer.invoke("hotkeys:reregister"),
  hotkeysStatus: () => ipcRenderer.invoke("hotkeys:status"),
  onHotkeysStatus: (cb) => ipcRenderer.on("hotkeys-status", (_e, s) => cb(s)),
  setWindowOpacity: (v) => ipcRenderer.invoke("window:setOpacity", v),
  // v0.4.0 — account + cloud sync
  accountStatus: () => ipcRenderer.invoke("account:status"),
  accountSignIn: () => ipcRenderer.invoke("account:signIn"),
  accountCancelSignIn: () => ipcRenderer.invoke("account:cancelSignIn"),
  accountGetUsername: () => ipcRenderer.invoke("account:getUsername"),
  accountSetUsername: (name) => ipcRenderer.invoke("account:setUsername", { name }),
  accountCheckUsername: (name) => ipcRenderer.invoke("account:checkUsername", { name }),
  accountSignOut: () => ipcRenderer.invoke("account:signOut"),
  accountOpenWeb: (p) => ipcRenderer.invoke("account:openWeb", p),
  syncPush: (opts) => ipcRenderer.invoke("sync:push", opts || {}),
  syncPull: (opts) => ipcRenderer.invoke("sync:pull", opts || {}),
  onAccountChanged: (cb) => ipcRenderer.on("account-changed", (_e, s) => cb(s)),
  onSyncStatus: (cb) => ipcRenderer.on("sync-status", (_e, s) => cb(s)),
  // v0.5.0 — back/forward nav, stats, api-key validate
  wpBack: () => ipcRenderer.invoke("wp:back"),
  wpForward: () => ipcRenderer.invoke("wp:forward"),
  setPaused: (v) => ipcRenderer.invoke("wp:setPaused", v),
  statsGet: () => ipcRenderer.invoke("stats:get"),
  statsReset: () => ipcRenderer.invoke("stats:reset"),
  gameRecord: (score) => ipcRenderer.invoke("game:record", score),
  apiKeyValidate: (key) => ipcRenderer.invoke("apikey:validate", key),
  sendFeedback: (payload) => ipcRenderer.invoke("feedback:send", payload),
  crashList: () => ipcRenderer.invoke("crash:list"),
  crashPreview: () => ipcRenderer.invoke("crash:preview"),
  crashClear: () => ipcRenderer.invoke("crash:clear"),
  onAppToast: (cb) => ipcRenderer.on("app-toast", (_e, s) => cb(s)),
  // v0.6.0 — preset library + community presets
  presetBuiltins: () => ipcRenderer.invoke("presets:builtins"),
  presetBrowse: (opts) => ipcRenderer.invoke("presets:browse", opts || {}),
  presetPublish: (opts) => ipcRenderer.invoke("presets:publish", opts || {}),
  presetThumb: (opts) => ipcRenderer.invoke("presets:thumb", opts || {}),
  presetRenameAuthor: (opts) => ipcRenderer.invoke("presets:rename-author", opts || {}),
  presetUnpublish: (opts) => ipcRenderer.invoke("presets:unpublish", opts || {}),
  presetLike: (opts) => ipcRenderer.invoke("presets:like", opts || {}),
  presetCopied: (opts) => ipcRenderer.invoke("presets:copied", opts || {}),
  presetShareable: () => ipcRenderer.invoke("presets:shareable"),
  onChanged: (cb) => ipcRenderer.on("wallpaper-changed", (_e, info) => cb(info)),
  onConfigChanged: (cb) => ipcRenderer.on("config-changed", (_e, cfg) => cb(cfg)),
});
