/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as LinkRouteImport } from './routes/link'
import { Route as PresetsRouteImport } from './routes/presets'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminStatsRouteImport } from './routes/admin/stats'
import { Route as ApiPublicFeedbackRouteImport } from './routes/api/public/feedback'
import { Route as ApiPublicPairPollRouteImport } from './routes/api/public/pair/poll'
import { Route as ApiPublicPairStartRouteImport } from './routes/api/public/pair/start'
import { Route as ApiPublicPresetsCopiedRouteImport } from './routes/api/public/presets/copied'
import { Route as ApiPublicPresetsImageRouteImport } from './routes/api/public/presets/image'
import { Route as ApiPublicPresetsThumbRouteImport } from './routes/api/public/presets/thumb'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkRoute = LinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => rootRouteImport,
} as any)
const PresetsRoute = PresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/admin/stats',
  path: '/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedbackRoute = ApiPublicFeedbackRouteImport.update({
  id: '/api/public/feedback',
  path: '/api/public/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPairPollRoute = ApiPublicPairPollRouteImport.update({
  id: '/api/public/pair/poll',
  path: '/api/public/pair/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPairStartRoute = ApiPublicPairStartRouteImport.update({
  id: '/api/public/pair/start',
  path: '/api/public/pair/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPresetsCopiedRoute = ApiPublicPresetsCopiedRouteImport.update({
  id: '/api/public/presets/copied',
  path: '/api/public/presets/copied',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPresetsImageRoute = ApiPublicPresetsImageRouteImport.update({
  id: '/api/public/presets/image',
  path: '/api/public/presets/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPresetsThumbRoute = ApiPublicPresetsThumbRouteImport.update({
  id: '/api/public/presets/thumb',
  path: '/api/public/presets/thumb',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/link': typeof LinkRoute
  '/presets': typeof PresetsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/stats': typeof AdminStatsRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/pair/poll': typeof ApiPublicPairPollRoute
  '/api/public/pair/start': typeof ApiPublicPairStartRoute
  '/api/public/presets/copied': typeof ApiPublicPresetsCopiedRoute
  '/api/public/presets/image': typeof ApiPublicPresetsImageRoute
  '/api/public/presets/thumb': typeof ApiPublicPresetsThumbRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/link': typeof LinkRoute
  '/presets': typeof PresetsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/stats': typeof AdminStatsRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/pair/poll': typeof ApiPublicPairPollRoute
  '/api/public/pair/start': typeof ApiPublicPairStartRoute
  '/api/public/presets/copied': typeof ApiPublicPresetsCopiedRoute
  '/api/public/presets/image': typeof ApiPublicPresetsImageRoute
  '/api/public/presets/thumb': typeof ApiPublicPresetsThumbRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/link': typeof LinkRoute
  '/presets': typeof PresetsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/stats': typeof AdminStatsRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/pair/poll': typeof ApiPublicPairPollRoute
  '/api/public/pair/start': typeof ApiPublicPairStartRoute
  '/api/public/presets/copied': typeof ApiPublicPresetsCopiedRoute
  '/api/public/presets/image': typeof ApiPublicPresetsImageRoute
  '/api/public/presets/thumb': typeof ApiPublicPresetsThumbRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/changelog'
    | '/link'
    | '/presets'
    | '/privacy'
    | '/reset-password'
    | '/admin/stats'
    | '/api/public/feedback'
    | '/api/public/pair/poll'
    | '/api/public/pair/start'
    | '/api/public/presets/copied'
    | '/api/public/presets/image'
    | '/api/public/presets/thumb'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/changelog'
    | '/link'
    | '/presets'
    | '/privacy'
    | '/reset-password'
    | '/admin/stats'
    | '/api/public/feedback'
    | '/api/public/pair/poll'
    | '/api/public/pair/start'
    | '/api/public/presets/copied'
    | '/api/public/presets/image'
    | '/api/public/presets/thumb'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/changelog'
    | '/link'
    | '/presets'
    | '/privacy'
    | '/reset-password'
    | '/admin/stats'
    | '/api/public/feedback'
    | '/api/public/pair/poll'
    | '/api/public/pair/start'
    | '/api/public/presets/copied'
    | '/api/public/presets/image'
    | '/api/public/presets/thumb'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  ChangelogRoute: typeof ChangelogRoute
  LinkRoute: typeof LinkRoute
  PresetsRoute: typeof PresetsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminStatsRoute: typeof AdminStatsRoute
  ApiPublicFeedbackRoute: typeof ApiPublicFeedbackRoute
  ApiPublicPairPollRoute: typeof ApiPublicPairPollRoute
  ApiPublicPairStartRoute: typeof ApiPublicPairStartRoute
  ApiPublicPresetsCopiedRoute: typeof ApiPublicPresetsCopiedRoute
  ApiPublicPresetsImageRoute: typeof ApiPublicPresetsImageRoute
  ApiPublicPresetsThumbRoute: typeof ApiPublicPresetsThumbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link': {
      id: '/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof LinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presets': {
      id: '/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof PresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/admin/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feedback': {
      id: '/api/public/feedback'
      path: '/api/public/feedback'
      fullPath: '/api/public/feedback'
      preLoaderRoute: typeof ApiPublicFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pair/poll': {
      id: '/api/public/pair/poll'
      path: '/api/public/pair/poll'
      fullPath: '/api/public/pair/poll'
      preLoaderRoute: typeof ApiPublicPairPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pair/start': {
      id: '/api/public/pair/start'
      path: '/api/public/pair/start'
      fullPath: '/api/public/pair/start'
      preLoaderRoute: typeof ApiPublicPairStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/presets/copied': {
      id: '/api/public/presets/copied'
      path: '/api/public/presets/copied'
      fullPath: '/api/public/presets/copied'
      preLoaderRoute: typeof ApiPublicPresetsCopiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/presets/image': {
      id: '/api/public/presets/image'
      path: '/api/public/presets/image'
      fullPath: '/api/public/presets/image'
      preLoaderRoute: typeof ApiPublicPresetsImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/presets/thumb': {
      id: '/api/public/presets/thumb'
      path: '/api/public/presets/thumb'
      fullPath: '/api/public/presets/thumb'
      preLoaderRoute: typeof ApiPublicPresetsThumbRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  ChangelogRoute: ChangelogRoute,
  LinkRoute: LinkRoute,
  PresetsRoute: PresetsRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminStatsRoute: AdminStatsRoute,
  ApiPublicFeedbackRoute: ApiPublicFeedbackRoute,
  ApiPublicPairPollRoute: ApiPublicPairPollRoute,
  ApiPublicPairStartRoute: ApiPublicPairStartRoute,
  ApiPublicPresetsCopiedRoute: ApiPublicPresetsCopiedRoute,
  ApiPublicPresetsImageRoute: ApiPublicPresetsImageRoute,
  ApiPublicPresetsThumbRoute: ApiPublicPresetsThumbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
